on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: 887eccb0ccc54936b06995fa941e2237.azurecr.io
        username: ${{ secrets.acr_887eccb0ccc54936b06995fa941e2237_username }}
        password: ${{ secrets.acr_887eccb0ccc54936b06995fa941e2237_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/m" -f  "." -t 887eccb0ccc54936b06995fa941e2237.azurecr.io/limacluster:${{ github.sha }} --label dockerfile-path=.
        docker push 887eccb0ccc54936b06995fa941e2237.azurecr.io/limacluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_limacluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep limaclusterb30b | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace limaclusterb30b`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: limaclusterb30b
        container-registry-url: 887eccb0ccc54936b06995fa941e2237.azurecr.io
        container-registry-username: ${{ secrets.acr_887eccb0ccc54936b06995fa941e2237_username }}
        container-registry-password: ${{ secrets.acr_887eccb0ccc54936b06995fa941e2237_password }}
        secret-name: limaclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: limaclusterb30b
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          887eccb0ccc54936b06995fa941e2237.azurecr.io/limacluster:${{ github.sha }}
        imagepullsecrets: |
          limaclusterdockerauth
